# SvelteKit Frontend Application
frontend:
  build:
    context: ./res-ads
    dockerfile: Dockerfile
  container_name: resads-frontend
  restart: always
  depends_on:
    db:
      condition: service_healthy
  ports:
    - "3000:3000"
  environment:
    DATABASE_URL: postgres://resads_user:resads_password@db:5432/resads
    NODE_ENV: production
  healthcheck:
    test: ["CMD-SHELL", "wget -q --spider http://localhost:3000 || exit 1"]
    interval: 30s
    timeout: 10s
    retries: 3
    start_period: 30s
